language: java
sudo: false

jdk:
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
  - openjdk12

env:
  - DSPLAY=:0

before_script:
  - pip install --user codecov

after_success:
  - bash <(curl -s https://codecov.io/bash)

test:
  post:
  - if [ -e ./gradlew ]; then ./gradlew --daemon jacocoTestReport;else gradle --daemon jacocoTestReport;fi

env:
  global:
  - TERM=dumb
  - GRADLE_OPTS="-Xmx768m -Xms256m -XX:MaxPermSize=256m -XX:+CMSClassUnloadingEnabled"

after_failure: ./travis-failure.sh

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
