language: java
jdk:
  - oraclejdk8
env:
  - DSPLAY=:0
before_script:
  - pip install --user codecov

after_success:
  - codecov

env:
  global:
  - TERM=dumb
  - GRADLE_OPTS="-Xmx768m -Xms256m -XX:MaxPermSize=256m -XX:+CMSClassUnloadingEnabled"

after_failure: ./travis-after-failure.sh
