name: Gradle CI

on:
  push:
  pull_request:

jobs:   
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v5
    - name: Setup JDK
      uses: actions/setup-java@v5
      with:
        distribution: "temurin"
        java-version: "17"
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
    - name: Run build with Gradle wrapper
      run: ./gradlew build --scan

    # MUST only be done once using ubuntu as reference operating system
    - name: Upload build reports
      uses: actions/upload-artifact@v4
      if: matrix.os == 'ubuntu-latest'
      with:
        name: build-reports
        path: build/reports/

    - name: Show test Summary
      uses: test-summary/action@v2
      with:
        paths: "./build/test-results/test/TEST-*.xml"
      if: always()

    - name: Code coverage with codecov
      uses: codecov/codecov-action@v5
      if: matrix.os == 'ubuntu-latest'
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
